name: Auto Cancel

on: [push]

jobs:
  cancel:
    name: 'Cancel Previous Runs'
    # Skip if push is from PR fork.
    if: github.event.pull_request.head.repo.fork == false
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
        with:
          workflow_id: build-test-measure.yml
          access_token: ${{ github.token }}
