name: Cancel

on: [push]

jobs:
  cancel:
    name: 'Previous Runs'
    # Skip if push is from PR fork.
    if: github.event.pull_request.head.repo.fork == false
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.8.0
        with:
          workflow_id: 1364807 # ID of the `build-test-measure` workflow
          access_token: ${{ github.token }}
